19/05/22 (18:43:41) | ERROR: [Errno 2] No such file or directory: '/home/xurr/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/xurr/.config/bpytop/themes'
30/05/22 (11:15:37) | ERROR: [Errno 2] No such file or directory: '/home/xurr/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/xurr/.config/bpytop/themes'
